name: cs3midlogin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  another_carousel_pro: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - "assets/loginImages/coffee.jpg"
    - "assets/loginImages/coffee1.jpg"
    - "assets/loginImages/coffee2.jpg"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
